### ISSUE TITLE
Algunas dudas practica Formularios (Pablo de Madaria)

### ISSUE THREAD

**Issue by PDMP2122** [PDMP2122/practica_dwec_gestor_presupuesto#1]
Buenas tardes @pedroprieto

Tengo algunas dudas sobre la practica de formularios:

1.- En las lineas 270 y 271 de gestionPresupuestoWeb, he creado unas variables para poder acceder a gasto y botonEditarFormulario desde la funcion submitFormularioEdit. Funciona bien, pero no se si es muy correcto hacerlo así.

2.- En el mismo archivo, no tengo muy claro como reutilizar la el objeto manejador del botón cancelar (linea 244), ya que no puedo acceder al botón editar del gasto para ponerle la propiedad disabled a false.

Gracias anticipadamente

Un saludo

**Comment by pedroprieto** [comment]
Buenas,
1. Es una opción. En este caso estás utilizando el contexto léxico en lugar de `this`. Otra opción es la misma que la que has hecho en la práctica de eventos: crear un objeto manejador de eventos para el envío del formulario y asignarle la propiedad `gasto`.
2. Tienes acceso al formulario en esta variable:
  https://github.com/PDMP2122/practica_dwec_gestor_presupuesto/blob/5dc179764449606c951d627116ba192e2a2066fc/js/gestionPresupuestoWeb.js#L239
  Puedes utilizarla para buscar el botón dentro. Otra opción es pasar una referencia a `evento.currentTarget`, siendo `evento` el parámetro de esta función:
  https://github.com/PDMP2122/practica_dwec_gestor_presupuesto/blob/5dc179764449606c951d627116ba192e2a2066fc/js/gestionPresupuestoWeb.js#L207
  ya que es el botón de envío. Así, debajo de esta línea:
  https://github.com/PDMP2122/practica_dwec_gestor_presupuesto/blob/5dc179764449606c951d627116ba192e2a2066fc/js/gestionPresupuestoWeb.js#L239
  puedes poner:
    ```js
     cancelarManejador.botonNuevoGasto = evento.currentTarget; 
    ```

**Comment by PDMP2122** [comment]
Buenas tardes @pedroprieto 
Gracias por la respuesta.
En el punto 1 he creado el objeto manejador de eventos y he cambiado la función pero me da error:
![2024-11-13_17h12_46](https://github.com/user-attachments/assets/1ff87d4b-5645-4137-a0fb-cbcdf143fa0b)
![2024-11-13_17h13_07](https://github.com/user-attachments/assets/de7e249b-7139-4fba-9648-c8d3b01562f0)


En el punto 2 he intentado hacer lo que me comentas pero me da un error que no encuentra el botón. No se si será porque este código esta dentro de nuevoGastoWebFormulario, y el elemento que necesito es el botón Editar creado en cada gasto.
![2024-11-13_16h55_02](https://github.com/user-attachments/assets/ab61b7c4-5f46-4e1c-a337-de13621e0dd3)
![2024-11-13_16h57_05](https://github.com/user-attachments/assets/b8f47c68-f8a6-4243-a0eb-5154aebd14c7)

¿Que podría estar pasando?

**Comment by pedroprieto** [comment]
En el punto 1, estás usando la variable `submitFormularioEdit` antes de definirla. Sube la definición antes de la línea con `Object.create`. Aunque creo que ya está solucionado...

Con respecto a cancelar y volver a mostrar el botón, el problema es que usas el mismo manejador de cancelar para añadir y para editar gastos. Puedes hacer algo como lo siguiente:
- En la función siguiente, añade este código:
  https://github.com/PDMP2122/practica_dwec_gestor_presupuesto/blob/5dc179764449606c951d627116ba192e2a2066fc/js/gestionPresupuestoWeb.js#L245
  ```js
    if (this.botonEditar)
      this.botonEditar.disabled = false
  ```
- Y a continuación de esta línea:
  https://github.com/PDMP2122/practica_dwec_gestor_presupuesto/blob/5dc179764449606c951d627116ba192e2a2066fc/js/gestionPresupuestoWeb.js#L294
  añade lo siguiente:
  ```js
  cancelarManejador.botonEditar= botonEditarFormulario;
  ```

De esta manera, activarás el botón solo si existe (en el caso de Editar, no en el de Crear).

Un saludo!!

**Comment by PDMP2122** [comment]
@pedroprieto Solucionado!! Muchas gracias!
